# -*- coding: utf-8 -*-
"""ML2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gh8f0O07jJgh3NLusV1mjteAGFGjGmbB
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import time
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from tensorflow.keras.datasets import fashion_mnist

# 1. Load the Fashion-MNIST dataset
print("Loading Fashion-MNIST data...")
(x_train_full, y_train_full), (x_test, y_test) = fashion_mnist.load_data()

# Define class names for reference
class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

# 2. Normalize pixel values to the [0, 1] range
x_train_full = x_train_full.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

# 3. Split data into Training and Validation sets (e.g., 80% Train, 20% Val)
x_train, x_val, y_train, y_val = train_test_split(
    x_train_full, y_train_full, test_size=0.2, random_state=42
)

# 4. Flattening: Convert 28x28 images into 784-dimensional vectors
# (Required for PCA and traditional Clustering algorithms)
x_train_flat = x_train.reshape((len(x_train), -1))
x_val_flat = x_val.reshape((len(x_val), -1))
x_test_flat = x_test.reshape((len(x_test), -1))

print(f"Train set shape: {x_train_flat.shape}")
print(f"Validation set shape: {x_val_flat.shape}")
print(f"Test set shape: {x_test_flat.shape}")

# Start timing the training process
start_time = time.time()

# Create and fit PCA
# We keep enough components to explain 95% of the variance
pca = PCA(n_components=0.95)
pca.fit(x_train_flat)

pca_train_time = time.time() - start_time

# Transform (encode) the test set into the reduced PCA space
x_test_pca = pca.transform(x_test_flat)

print(f"PCA Training Time: {pca_train_time:.2f} seconds")
print(f"Original dimensions: 784")
print(f"Reduced dimensions (PCA): {pca.n_components_}")

# Reconstruct images from the reduced PCA space back to original space
x_test_reconstructed = pca.inverse_transform(x_test_pca)

plt.figure(figsize=(10, 4))
for i in range(5):
    # Original image plot
    plt.subplot(2, 5, i + 1)
    plt.imshow(x_test[i], cmap='gray')
    plt.title("Original")
    plt.axis('off')

    # Reconstructed image plot
    plt.subplot(2, 5, i + 6)
    plt.imshow(x_test_reconstructed[i].reshape(28, 28), cmap='gray')
    plt.title("PCA Rec")
    plt.axis('off')

plt.tight_layout()
plt.show()

import time
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models

# 1. Define the architecture
input_dim = 784 # 28x28 images
encoding_dim = 32 # Target bottleneck size

# 2. Build the Encoder
encoder_input = layers.Input(shape=(input_dim,))
x = layers.Dense(128, activation='relu')(encoder_input)
x = layers.Dense(64, activation='relu')(x)
encoder_output = layers.Dense(encoding_dim, activation='relu')(x)

encoder = models.Model(encoder_input, encoder_output, name="Encoder")

# 3. Build the Decoder
decoder_input = layers.Input(shape=(encoding_dim,))
x = layers.Dense(64, activation='relu')(decoder_input)
x = layers.Dense(128, activation='relu')(x)
decoder_output = layers.Dense(input_dim, activation='sigmoid')(x)

decoder = models.Model(decoder_input, decoder_output, name="Decoder")

# 4. Combine to create the Autoencoder
autoencoder_input = layers.Input(shape=(input_dim,))
encoded_repr = encoder(autoencoder_input)
decoded_repr = decoder(encoded_repr)
autoencoder = models.Model(autoencoder_input, decoded_repr, name="Autoencoder")

# 5. Compile the model
autoencoder.compile(optimizer='adam', loss='mse')

# 6. Train the model using Train and Validation data
print("Training Stacked Autoencoder...")
# Start timing the SAE training process
start_time_sae = time.time()

history = autoencoder.fit(
    x_train_flat, x_train_flat,
    epochs=20,
    batch_size=256,
    shuffle=True,
    validation_data=(x_val_flat, x_val_flat),
    verbose=1
)

# Calculate elapsed time
sae_train_time = time.time() - start_time_sae
print(f"SAE Training Time: {sae_train_time:.2f} seconds")

# 7. Use only the Encoder to reduce dimensions of the test set
x_test_sae = encoder.predict(x_test_flat)

# Reconstruct images using the full autoencoder
x_test_reconstructed_sae = autoencoder.predict(x_test_flat)

plt.figure(figsize=(10, 4))
for i in range(5):
    # Original image
    plt.subplot(2, 5, i + 1)
    plt.imshow(x_test[i], cmap='gray')
    plt.title("Original")
    plt.axis('off')

    # SAE Reconstructed image
    plt.subplot(2, 5, i + 6)
    plt.imshow(x_test_reconstructed_sae[i].reshape(28, 28), cmap='gray')
    plt.title("SAE Rec")
    plt.axis('off')

plt.tight_layout()
plt.show()

# Initialize the results list
results_data = []

def log_results(dim_red_name, cluster_alg_name, train_time, exec_time,
                n_clusters, ch_score, db_score, sil_score, custom_metric):
    """
    Appends performance metrics to the global results list.
    """
    results_data.append({
        "Dim. Red. Technique": dim_red_name,
        "Clustering Algorithm": cluster_alg_name,
        "Training Time (s)": round(train_time, 4),
        "Execution Time (s)": round(exec_time, 4),
        "Suggested Clusters": n_clusters,
        "Calinski-Harabasz": round(ch_score, 4),
        "Davies-Bouldin": round(db_score, 4),
        "Silhouette": round(sil_score, 4),
        "Adjusted Rand Index": round(custom_metric, 4) # Our 4th metric choice
    })

# Note: We will convert this list to a Pandas DataFrame at the end.

from sklearn.decomposition import TruncatedSVD
from sklearn.mixture import GaussianMixture
from sklearn.cluster import MiniBatchKMeans, DBSCAN
from sklearn import metrics

# --- 3rd Dim. Reduction Technique: TruncatedSVD ---
print("Running TruncatedSVD...")
start_time = time.time()
tsvd = TruncatedSVD(n_components=50, random_state=42)
tsvd.fit(x_train_flat)
tsvd_train_time = time.time() - start_time
x_test_tsvd = tsvd.transform(x_test_flat)

# --- 4th Metric Selection: Adjusted Rand Index (ARI) ---
# ARI compares clusters with the real labels (y_test)
# Score: 1.0 is perfect, 0.0 is random.

# Dictionary to hold our transformed datasets
datasets = {
    "Raw": x_test_flat,
    "PCA": x_test_pca,
    "SAE": x_test_sae,
    "TruncatedSVD": x_test_tsvd
}

# Training times for Dim. Red. (recorded during their fits)
dim_red_times = {
    "Raw": 0.0,
    "PCA": pca_train_time,
    "SAE": sae_train_time,
    "TruncatedSVD": tsvd_train_time
}

def run_clustering_suite(data_name, data_encoded, labels_true):
    print(f"\nProcessing Dataset: {data_name}")

    # Define Clustering Algorithms
    # 1. MiniBatchKMeans (Required)
    # 2. DBSCAN (Required)
    # 3. GMM (Choice)
    algorithms = {
        "MiniBatchKMeans": MiniBatchKMeans(n_clusters=10, batch_size=256, random_state=42),
        "DBSCAN": DBSCAN(eps=0.5, min_samples=5), # Parameters might need tuning
        "GMM": GaussianMixture(n_components=10, random_state=42)
    }

    for alg_name, model in algorithms.items():
        print(f"  Running {alg_name}...")

        start_exec = time.time()
        if alg_name == "GMM":
            cluster_labels = model.fit_predict(data_encoded)
        else:
            cluster_labels = model.fit_predict(data_encoded)
        exec_time = time.time() - start_exec

        # Number of clusters (DBSCAN might find more or less than 10)
        n_clusters = len(set(cluster_labels)) - (1 if -1 in cluster_labels else 0)

        # Performance Metrics (using a sample for Silhouette to save time)
        if n_clusters > 1:
            ch_idx = metrics.calinski_harabasz_score(data_encoded, cluster_labels)
            db_idx = metrics.davies_bouldin_score(data_encoded, cluster_labels)

            # Sampling for speed
            sample_indices = np.random.choice(len(data_encoded), size=min(2000, len(data_encoded)), replace=False)
            sil_score = metrics.silhouette_score(data_encoded[sample_indices], cluster_labels[sample_indices])

            ari_score = metrics.adjusted_rand_score(labels_true, cluster_labels)
        else:
            ch_idx, db_idx, sil_score, ari_score = 0, 0, 0, 0

        # Log results to the list
        log_results(data_name, alg_name, dim_red_times[data_name], exec_time,
                    n_clusters, ch_idx, db_idx, sil_score, ari_score)

# Execute the loop for all 4 data versions
for name, data in datasets.items():
    run_clustering_suite(name, data, y_test)

# Convert results to DataFrame
results_df = pd.DataFrame(results_data)
print("\nTask Complete! Displaying Results:")
display(results_df)

import matplotlib.pyplot as plt
import numpy as np

# Safety check: Ensure the image data is available under the right name
try:
    data_to_plot = x_test_full
except NameError:
    data_to_plot = x_test # Fallback to x_test if x_test_full is missing

# 1. Generate labels from our best model (SAE + MiniBatchKMeans)
best_model = MiniBatchKMeans(n_clusters=10, batch_size=256, random_state=42)
best_labels = best_model.fit_predict(x_test_sae)

# 2. Function to plot the grid
def plot_cluster_grid(data_images, labels, n_clusters=4):
    plt.figure(figsize=(15, 10))
    # Select the first 4 clusters to display
    selected_clusters = [0, 1, 2, 3]

    for i, cluster_id in enumerate(selected_clusters):
        # Get indices of images in this cluster
        cluster_indices = np.where(labels == cluster_id)[0]

        # Pick 5 random images from this cluster
        if len(cluster_indices) >= 5:
            sample_indices = np.random.choice(cluster_indices, 5, replace=False)
        else:
            sample_indices = cluster_indices # If cluster is very small

        for j, img_idx in enumerate(sample_indices):
            plt.subplot(n_clusters, 5, i * 5 + j + 1)
            # Ensure we reshape to 28x28 for display
            plt.imshow(data_images[img_idx].reshape(28, 28), cmap='gray')
            if j == 0:
                plt.ylabel(f"Cluster {cluster_id}", fontsize=14, fontweight='bold')
            plt.axis('off')

    plt.suptitle("Indicative Grouping Results (SAE + MiniBatchKMeans)", fontsize=16)
    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()

# Run the plotting function
plot_cluster_grid(data_to_plot, best_labels)

import seaborn as sns

# Create a barplot for Silhouette scores across different techniques
plt.figure(figsize=(12, 6))
sns.barplot(data=results_df, x="Dim. Red. Technique", y="Silhouette", hue="Clustering Algorithm")
plt.title("Comparison of Silhouette Scores (Higher is Better)")
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.show()

# Create a barplot for Execution Times
plt.figure(figsize=(12, 6))
sns.barplot(data=results_df, x="Dim. Red. Technique", y="Execution Time (s)", hue="Clustering Algorithm")
plt.yscale('log') # Use log scale because GMM is much slower than others
plt.title("Execution Time Comparison (Log Scale)")
plt.ylabel("Seconds (Log)")
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.show()

results_df.to_excel("clustering_results.xlsx", index=False)